apiVersion: apps/v1
kind: Deployment
metadata:
  name: bykovd-lab1-5
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 1
  selector:
    matchLabels:
      app: bykovd-lab1.5
  template:
    metadata:
      labels:
        app: bykovd-lab1.5
    spec:
      containers:
      - name: bykovd-lab1-5
        image: bykovd1984/softwarearchitect-lab1.5:1.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bykovd-lab1-5-nodeport
spec:
  type: NodePort
  selector:
    app: bykovd-lab1.5
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30123
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /student/$1
  name: rewrite
  namespace: default
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - backend:
          serviceName: bykovd-lab1-5-nodeport
          servicePort: 80
        path: /otusapp/(.*)
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: bykovd-lab1-5-nodeport
          servicePort: 80        



  